version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
    ports:
      - "27017:27017"
  app:
    build:
      context: .
    command: npm start
    depends_on:
      - mongo